services:
  generate:
    image: node:18
    volumes:
      - ./scripts/loadtest:/scripts
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    working_dir: /scripts
    entrypoint: sh
    command: ./scripts/run.sh
    env_file:
      - .env.loadtest
    networks:
      - express-gateway-network

  loadtest:
    image: grafana/k6
    depends_on:
      generate:
        condition: service_completed_successfully
    volumes:
      - ./scripts/loadtest:/scripts
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    working_dir: /scripts
    entrypoint: sh
    command: ./scripts/entrypoint.sh
    env_file:
      - .env.loadtest
    networks:
      - express-gateway-network

networks:
  express-gateway-network:
    driver: bridge

