version: "3.9"

services:
  express:
    container_name: express
    build:
      context: ./
      target: ${TARGET_STAGE:-development}
      args:
        NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${DEV_PORT:-8000}:${DEV_PORT:-8000}"
      - "${DEV_DEBUG_PORT:-9229}:${DEV_DEBUG_PORT:-9229}"
    volumes:
      - .:/usr/src/app
      - ./dist/client:/usr/src/app/dist/client
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    env_file:
      - .env
    entrypoint: ./scripts/docker/start-app.sh
    depends_on:
      - db
      - redis
    networks:
      - express-gateway-network

  worker:
    container_name: worker
    build:
      context: ./
      target: ${TARGET_STAGE:-development}
      args:
        NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - .:/usr/src/app
      - ./dist/client:/usr/src/app/dist/client
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
      - ./scripts/docker/start-worker.sh:/start-worker.sh
    env_file:
      - .env
    entrypoint: /start-worker.sh
    depends_on:
      - express
      - db
      - redis
    networks:
      - express-gateway-network

  db:
    container_name: postgres
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - express-gateway-network

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    env_file:
      - .env
    networks:
      - express-gateway-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.cors.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - express-gateway-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.6
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
      - ./scripts/docker/start-kibana.sh:/start-kibana.sh
    entrypoint: /start-kibana.sh
    depends_on:
      - elasticsearch
    networks:
      - express-gateway-network

networks:
  express-gateway-network:
    driver: bridge

volumes:
  esdata:
    driver: local

