version: "3.9"

services:
  express:
    container_name: express
    build:
      context: ./
      target: ${TARGET_STAGE:-development}
      args:
        NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${DEV_PORT:-8000}:${DEV_PORT:-8000}"
      - "${DEV_DEBUG_PORT:-9229}:${DEV_DEBUG_PORT:-9229}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - express-gateway-network
  db:
    container_name: postgres
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - express-gateway-network
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    env_file:
      - .env
    networks:
      - express-gateway-network
networks:
  express-gateway-network:
    driver: bridge

